/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2025-10-27 23:14:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.components;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DsInicioGuest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1761606832859L));
    _jspx_dependants.put("jar:file:/D:/Erick/Documentos/UTP/web%20integrado/enroute_aqp/enroute_aqp1/build/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // Obtener información de sesión si existe (sin forzar login)
    String userName = (String) session.getAttribute("userName");
    String userEmail = (String) session.getAttribute("userEmail");
    Boolean isAdminObj = (Boolean) session.getAttribute("isAdmin");
    boolean isAdmin = isAdminObj != null && isAdminObj.booleanValue();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Enroute AQP - Invitado</title>\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Bootstrap Icons -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Leaflet CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/leaflet@1.9.4/dist/leaflet.css\" />\r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"font-family: 'Plus Jakarta Sans', sans-serif; height: 100vh; overflow-y: auto;\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"d-flex h-100\">\r\n");
      out.write("        <!-- Mobile Menu Toggle Button -->\r\n");
      out.write("        <button class=\"d-lg-none position-fixed top-0 start-0 m-3\" \r\n");
      out.write("                type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#mobileSidebar\" \r\n");
      out.write("                style=\"z-index: 1050; background: #343a40; color: white; border: none; box-shadow: none; padding: 8px 12px; border-radius: 6px;\">\r\n");
      out.write("            <i class=\"bi bi-list fs-4\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <!-- Sidebar for Desktop -->\r\n");
      out.write("        <div class=\"bg-dark text-white d-none d-lg-flex flex-column\" style=\"width: 280px; min-height: 100vh;\">\r\n");
      out.write("            <!-- Logo -->\r\n");
      out.write("            <div class=\"p-4 border-bottom border-secondary\">\r\n");
      out.write("                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/icon_img.png\" alt=\"Logo\" style=\"height: 40px\" class=\"me-2\">\r\n");
      out.write("                    <h4 class=\"mb-0 fw-bold text-white\">Enroute AQP</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Navigation Menu (limited for guest) -->\r\n");
      out.write("            <nav class=\"py-3\">\r\n");
      out.write("                <ul class=\"nav nav-pills flex-column\">\r\n");
      out.write("                    <li class=\"nav-item mb-2\">\r\n");
      out.write("                        <a href=\"mapa.jsp\" class=\"nav-link text-white d-flex align-items-center px-4 py-3\">\r\n");
      out.write("                            <i class=\"bi bi-geo-alt me-3\"></i>\r\n");
      out.write("                            <span>Mapa</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item mb-2\">\r\n");
      out.write("                        <a href=\"login.jsp\" class=\"nav-link text-white d-flex align-items-center px-4 py-3\">\r\n");
      out.write("                            <i class=\"bi bi-box-arrow-in-right me-3\"></i>\r\n");
      out.write("                            <span>Iniciar sesión</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item mb-2\">\r\n");
      out.write("                        <a href=\"register.jsp\" class=\"nav-link text-white d-flex align-items-center px-4 py-3\">\r\n");
      out.write("                            <i class=\"bi bi-person-plus me-3\"></i>\r\n");
      out.write("                            <span>Registrarse</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Guest Info -->\r\n");
      out.write("            <div class=\"p-4 border-top border-secondary\">\r\n");
      out.write("                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    <div class=\"rounded-circle overflow-hidden me-3\" style=\"width: 50px; height: 50px;\">\r\n");
      out.write("                        <img src=\"https://avatars.githubusercontent.com/u/0?v=4\" alt=\"Guest Avatar\" \r\n");
      out.write("                             class=\"w-100 h-100 object-fit-cover\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"flex-grow-1\">\r\n");
      out.write("                        <h6 class=\"mb-0 text-white\">");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("</h6>\r\n");
      out.write("                        <small class=\"text-white\">");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Mobile Sidebar (Offcanvas) -->\r\n");
      out.write("        <div class=\"offcanvas offcanvas-start bg-dark text-white d-lg-none\" tabindex=\"-1\" id=\"mobileSidebar\">\r\n");
      out.write("            <div class=\"offcanvas-header border-bottom border-secondary\">\r\n");
      out.write("                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    <i class=\"bi bi-geo-alt-fill text-warning me-2 fs-4\"></i>\r\n");
      out.write("                    <h4 class=\"mb-0 fw-bold text-white\">Enroute AQP</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"offcanvas\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"offcanvas-body p-0\">\r\n");
      out.write("                <nav class=\"py-3\">\r\n");
      out.write("                    <ul class=\"nav nav-pills flex-column\">\r\n");
      out.write("                        <li class=\"nav-item mb-2\">\r\n");
      out.write("                            <a href=\"mapa.jsp\" class=\"nav-link text-white d-flex align-items-center px-4 py-3\">\r\n");
      out.write("                                <i class=\"bi bi-geo-alt me-3\"></i>\r\n");
      out.write("                                <span>Mapa</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item mb-2\">\r\n");
      out.write("                            <a href=\"login.jsp\" class=\"nav-link text-white d-flex align-items-center px-4 py-3\">\r\n");
      out.write("                                <i class=\"bi bi-box-arrow-in-right me-3\"></i>\r\n");
      out.write("                                <span>Iniciar sesión</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item mb-2\">\r\n");
      out.write("                            <a href=\"register.jsp\" class=\"nav-link text-white d-flex align-items-center px-4 py-3\">\r\n");
      out.write("                                <i class=\"bi bi-person-plus me-3\"></i>\r\n");
      out.write("                                <span>Registrarse</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /pages/components/DsInicioGuest.jsp(84,52) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userName != null ? sessionScope.userName : 'Invitado'}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent(null);
    // /pages/components/DsInicioGuest.jsp(85,50) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userEmail != null ? sessionScope.userEmail : 'Sin sesión'}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }
}
