/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2025-09-26 01:50:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // Verificar si el usuario está logueado
    String userEmail = (String) session.getAttribute("userEmail");
    if (userEmail == null) {
        response.sendRedirect("login.jsp");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Dashboard - Enroute AQP</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/landing-styles.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .dashboard-container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }        \r\n");
      out.write("        .dashboard-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .dashboard-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            background: #2c2c2c;\r\n");
      out.write("            }\r\n");
      out.write("            .icon-circle {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                width: 60px;\r\n");
      out.write("                height: 60px;\r\n");
      out.write("                border-radius: 50%;\r\n");
      out.write("                margin: 0 auto 20px auto;\r\n");
      out.write("                background: white;\r\n");
      out.write("                box-shadow: 0 2px 8px var(--color-principal);\r\n");
      out.write("            }\r\n");
      out.write("            .icon-circle svg {\r\n");
      out.write("                width: 32px;\r\n");
      out.write("                height: 32px;\r\n");
      out.write("                fill: black;\r\n");
      out.write("            }\r\n");
      out.write("        \r\n");
      out.write("        .logout-btn {\r\n");
      out.write("            background-color: #d32f2f;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .logout-btn:hover {\r\n");
      out.write("            background-color: #b71c1c;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("        <div class=\"navbar-logo\">\r\n");
      out.write("              <img src=\"../assets/icon_img.png\" alt=\"Logo\" style=\"width: 32px; height: 32px;\">\r\n");
      out.write("            <span>Enroute AQP</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"navbar-user\">\r\n");
      out.write("            <span class=\"navbar-user-name\">¡Bienvenido ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("!</span>\r\n");
      out.write("            <div class=\"navbar-avatar\">\r\n");
      out.write("                <img src=\"https://randomuser.me/api/portraits/men/44.jpg\" alt=\"Avatar\" />\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"dashboard-container\">\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"dashboard-grid\">\r\n");
      out.write("            <div class=\"dashboard-card\">\r\n");
      out.write("                    <div class=\"icon-circle\">\r\n");
      out.write("                       \r\n");
      out.write("                        <svg viewBox=\"0 0 24 24\"><path d=\"M20.5 3l-5.5 2.5-6-2.5-5.5 2.5v16l6-2.5 6 2.5 5.5-2.5v-16zm-6.5 17.11l-6-2.5v-13.61l6 2.5v13.61zm7-2.5l-5 2.27v-13.61l5-2.27v13.61z\"/></svg>\r\n");
      out.write("                    </div>\r\n");
      out.write("                <h3>Rutas Disponibles</h3>\r\n");
      out.write("                <p>Explora las rutas turísticas más populares de Arequipa</p>\r\n");
      out.write("                <button class=\"btn btn-primary\">Ver Rutas</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"dashboard-card\">\r\n");
      out.write("                    <div class=\"icon-circle\">\r\n");
      out.write("                        \r\n");
      out.write("                        <svg viewBox=\"0 0 24 24\"><path d=\"M12 12c2.7 0 5-2.3 5-5s-2.3-5-5-5-5 2.3-5 5 2.3 5 5 5zm0 2c-3.3 0-10 1.7-10 5v3h20v-3c0-3.3-6.7-5-10-5z\"/></svg>\r\n");
      out.write("                    </div>\r\n");
      out.write("                <h3>Mi Perfil</h3>\r\n");
      out.write("                <p>Gestiona tu información personal y preferencias</p>\r\n");
      out.write("                <button class=\"btn btn-primary\">Editar Perfil</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"dashboard-card\">\r\n");
      out.write("                    <div class=\"icon-circle\">\r\n");
      out.write("                        \r\n");
      out.write("                        <svg viewBox=\"0 0 24 24\"><path d=\"M12 21.35l-1.45-1.32c-5.05-4.6-8.35-7.6-8.35-11.07 0-2.54 2.07-4.61 4.61-4.61 1.74 0 3.41 1.01 4.19 2.61.78-1.6 2.45-2.61 4.19-2.61 2.54 0 4.61 2.07 4.61 4.61 0 3.47-3.3 6.47-8.35 11.07z\"/></svg>\r\n");
      out.write("                    </div>\r\n");
      out.write("                <h3>Favoritos</h3>\r\n");
      out.write("                <p>Revisa tus rutas y lugares favoritos guardados</p>\r\n");
      out.write("                <button class=\"btn btn-primary\">Ver Favoritos</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"dashboard-card\">\r\n");
      out.write("                    <div class=\"icon-circle\">\r\n");
      out.write("                        \r\n");
      out.write("                        <svg viewBox=\"0 0 24 24\"><path d=\"M12 8v5l4.28 2.54.72-1.21-3.5-2.08V8zm0-6c-5.52 0-10 4.48-10 10s4.48 10 10 10 10-4.48 10-10-4.48-10-10-10zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8z\"/></svg>\r\n");
      out.write("                    </div>\r\n");
      out.write("                <h3>Historial</h3>\r\n");
      out.write("                <p>Consulta tu historial de rutas visitadas</p>\r\n");
      out.write("                <button class=\"btn btn-primary\">Ver Historial</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div style=\"text-align: center; margin-top: 40px;\">\r\n");
      out.write("            <a href=\"../LogoutServlet\" class=\"logout-btn\">Cerrar Sesión</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
