/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2025-10-27 23:14:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_002dguest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/pages/components/DsFin.jsp", Long.valueOf(1761606832885L));
    _jspx_dependants.put("/pages/components/DsInicioGuest.jsp", Long.valueOf(1761606832893L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1761606832859L));
    _jspx_dependants.put("jar:file:/D:/Erick/Documentos/UTP/web%20integrado/enroute_aqp/enroute_aqp1/build/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // Obtener información de sesión si existe (sin forzar login)
    String userName = (String) session.getAttribute("userName");
    String userEmail = (String) session.getAttribute("userEmail");
    Boolean isAdminObj = (Boolean) session.getAttribute("isAdmin");
    boolean isAdmin = isAdminObj != null && isAdminObj.booleanValue();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Enroute AQP - Invitado</title>\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Bootstrap Icons -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Leaflet CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/leaflet@1.9.4/dist/leaflet.css\" />\r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"font-family: 'Plus Jakarta Sans', sans-serif; height: 100vh; overflow-y: auto;\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"d-flex h-100\">\r\n");
      out.write("        <!-- Mobile Menu Toggle Button -->\r\n");
      out.write("        <button class=\"d-lg-none position-fixed top-0 start-0 m-3\" \r\n");
      out.write("                type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#mobileSidebar\" \r\n");
      out.write("                style=\"z-index: 1050; background: #343a40; color: white; border: none; box-shadow: none; padding: 8px 12px; border-radius: 6px;\">\r\n");
      out.write("            <i class=\"bi bi-list fs-4\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <!-- Sidebar for Desktop -->\r\n");
      out.write("        <div class=\"bg-dark text-white d-none d-lg-flex flex-column\" style=\"width: 280px; min-height: 100vh;\">\r\n");
      out.write("            <!-- Logo -->\r\n");
      out.write("            <div class=\"p-4 border-bottom border-secondary\">\r\n");
      out.write("                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/icon_img.png\" alt=\"Logo\" style=\"height: 40px\" class=\"me-2\">\r\n");
      out.write("                    <h4 class=\"mb-0 fw-bold text-white\">Enroute AQP</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Navigation Menu (limited for guest) -->\r\n");
      out.write("            <nav class=\"py-3\">\r\n");
      out.write("                <ul class=\"nav nav-pills flex-column\">\r\n");
      out.write("                    <li class=\"nav-item mb-2\">\r\n");
      out.write("                        <a href=\"mapa.jsp\" class=\"nav-link text-white d-flex align-items-center px-4 py-3\">\r\n");
      out.write("                            <i class=\"bi bi-geo-alt me-3\"></i>\r\n");
      out.write("                            <span>Mapa</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item mb-2\">\r\n");
      out.write("                        <a href=\"login.jsp\" class=\"nav-link text-white d-flex align-items-center px-4 py-3\">\r\n");
      out.write("                            <i class=\"bi bi-box-arrow-in-right me-3\"></i>\r\n");
      out.write("                            <span>Iniciar sesión</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item mb-2\">\r\n");
      out.write("                        <a href=\"register.jsp\" class=\"nav-link text-white d-flex align-items-center px-4 py-3\">\r\n");
      out.write("                            <i class=\"bi bi-person-plus me-3\"></i>\r\n");
      out.write("                            <span>Registrarse</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Guest Info -->\r\n");
      out.write("            <div class=\"p-4 border-top border-secondary\">\r\n");
      out.write("                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    <div class=\"rounded-circle overflow-hidden me-3\" style=\"width: 50px; height: 50px;\">\r\n");
      out.write("                        <img src=\"https://avatars.githubusercontent.com/u/0?v=4\" alt=\"Guest Avatar\" \r\n");
      out.write("                             class=\"w-100 h-100 object-fit-cover\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"flex-grow-1\">\r\n");
      out.write("                        <h6 class=\"mb-0 text-white\">");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("</h6>\r\n");
      out.write("                        <small class=\"text-white\">");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Mobile Sidebar (Offcanvas) -->\r\n");
      out.write("        <div class=\"offcanvas offcanvas-start bg-dark text-white d-lg-none\" tabindex=\"-1\" id=\"mobileSidebar\">\r\n");
      out.write("            <div class=\"offcanvas-header border-bottom border-secondary\">\r\n");
      out.write("                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    <i class=\"bi bi-geo-alt-fill text-warning me-2 fs-4\"></i>\r\n");
      out.write("                    <h4 class=\"mb-0 fw-bold text-white\">Enroute AQP</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"offcanvas\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"offcanvas-body p-0\">\r\n");
      out.write("                <nav class=\"py-3\">\r\n");
      out.write("                    <ul class=\"nav nav-pills flex-column\">\r\n");
      out.write("                        <li class=\"nav-item mb-2\">\r\n");
      out.write("                            <a href=\"mapa.jsp\" class=\"nav-link text-white d-flex align-items-center px-4 py-3\">\r\n");
      out.write("                                <i class=\"bi bi-geo-alt me-3\"></i>\r\n");
      out.write("                                <span>Mapa</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item mb-2\">\r\n");
      out.write("                            <a href=\"login.jsp\" class=\"nav-link text-white d-flex align-items-center px-4 py-3\">\r\n");
      out.write("                                <i class=\"bi bi-box-arrow-in-right me-3\"></i>\r\n");
      out.write("                                <span>Iniciar sesión</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item mb-2\">\r\n");
      out.write("                            <a href=\"register.jsp\" class=\"nav-link text-white d-flex align-items-center px-4 py-3\">\r\n");
      out.write("                                <i class=\"bi bi-person-plus me-3\"></i>\r\n");
      out.write("                                <span>Registrarse</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Main Content -->\r\n");
      out.write("        <div class=\"flex-grow-1 d-flex flex-column\">\r\n");
      out.write("            <!-- Mobile Header with Menu Button -->\r\n");
      out.write("            <div class=\"bg-white d-lg-none p-3 shadow-sm\">\r\n");
      out.write("                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    <button class=\"btn btn-outline-dark me-3\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#mobileSidebar\">\r\n");
      out.write("                        <i class=\"bi bi-list\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                        <i class=\"bi bi-speedometer2 text-primary me-2\"></i>\r\n");
      out.write("                        <h5 class=\"mb-0 fw-bold\">Modo Invitado</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Dashboard Content -->\r\n");
      out.write("            <div class=\"dashboard-container p-3 p-lg-4\">\r\n");
      out.write("                <div class=\"row mb-4\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <h2 class=\"fw-bold text-dark mb-1\">Bienvenido a Enroute AQP</h2>\r\n");
      out.write("                        <p class=\"text-muted\">Estás explorando como invitado. <a href=\"register.jsp\" class=\"text-decoration-none fw-bold\">Regístrate</a> o <a href=\"login.jsp\" class=\"text-decoration-none fw-bold\">inicia sesión</a> para acceder a todas las funciones.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Alert Info -->\r\n");
      out.write("                <div class=\"row mb-4\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"alert alert-info d-flex align-items-center\" role=\"alert\">\r\n");
      out.write("                            <i class=\"bi bi-info-circle-fill me-3 fs-4\"></i>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <strong>Modo de prueba limitado</strong><br>\r\n");
      out.write("                                Solo puedes acceder al mapa. Regístrate para desbloquear todas las funcionalidades.\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Dashboard Cards con Bootstrap Grid -->\r\n");
      out.write("                <div class=\"row g-4\">\r\n");
      out.write("                    <!-- Mapa - HABILITADO -->\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                        <div class=\"card dashboard-card h-100 shadow\">\r\n");
      out.write("                            <div class=\"card-body text-center p-4\">\r\n");
      out.write("                                <div class=\"icon-circle bg-success\">\r\n");
      out.write("                                    <i class=\"bi bi-geo-alt text-white\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <h3 class=\"card-title\">Mapa Interactivo</h3>\r\n");
      out.write("                                <p class=\"card-text\">Explora el mapa de rutas de Arequipa</p>\r\n");
      out.write("                                <a href=\"mapa.jsp\" class=\"btn btn-success\">Ver Mapa</a>\r\n");
      out.write("                                <div class=\"mt-2\">\r\n");
      out.write("                                    <span class=\"badge bg-success\">Disponible</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Rutas - DESHABILITADO -->\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                        <div class=\"card dashboard-card h-100 bg-light\" style=\"opacity: 0.6;\">\r\n");
      out.write("                            <div class=\"card-body text-center p-4\">\r\n");
      out.write("                                <div class=\"icon-circle bg-secondary\">\r\n");
      out.write("                                    <i class=\"bi bi-map text-white\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <h3 class=\"card-title text-muted\">Rutas Disponibles</h3>\r\n");
      out.write("                                <p class=\"card-text text-muted\">Explora las rutas de Arequipa</p>\r\n");
      out.write("                                <button class=\"btn btn-secondary\" disabled>\r\n");
      out.write("                                    <i class=\"bi bi-lock-fill me-1\"></i> Bloqueado\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <div class=\"mt-2\">\r\n");
      out.write("                                    <span class=\"badge bg-secondary\">Requiere registro</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Perfil - DESHABILITADO -->\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                        <div class=\"card dashboard-card h-100 bg-light\" style=\"opacity: 0.6;\">\r\n");
      out.write("                            <div class=\"card-body text-center p-4\">\r\n");
      out.write("                                <div class=\"icon-circle bg-secondary\">\r\n");
      out.write("                                    <i class=\"bi bi-person text-white\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <h3 class=\"card-title text-muted\">Mi Perfil</h3>\r\n");
      out.write("                                <p class=\"card-text text-muted\">Gestiona tu información personal</p>\r\n");
      out.write("                                <button class=\"btn btn-secondary\" disabled>\r\n");
      out.write("                                    <i class=\"bi bi-lock-fill me-1\"></i> Bloqueado\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <div class=\"mt-2\">\r\n");
      out.write("                                    <span class=\"badge bg-secondary\">Requiere registro</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Favoritos - DESHABILITADO -->\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                        <div class=\"card dashboard-card h-100 bg-light\" style=\"opacity: 0.6;\">\r\n");
      out.write("                            <div class=\"card-body text-center p-4\">\r\n");
      out.write("                                <div class=\"icon-circle bg-secondary\">\r\n");
      out.write("                                    <i class=\"bi bi-heart text-white\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <h3 class=\"card-title text-muted\">Favoritos</h3>\r\n");
      out.write("                                <p class=\"card-text text-muted\">Guarda tus rutas favoritas</p>\r\n");
      out.write("                                <button class=\"btn btn-secondary\" disabled>\r\n");
      out.write("                                    <i class=\"bi bi-lock-fill me-1\"></i> Bloqueado\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <div class=\"mt-2\">\r\n");
      out.write("                                    <span class=\"badge bg-secondary\">Requiere registro</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Historial - DESHABILITADO -->\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                        <div class=\"card dashboard-card h-100 bg-light\" style=\"opacity: 0.6;\">\r\n");
      out.write("                            <div class=\"card-body text-center p-4\">\r\n");
      out.write("                                <div class=\"icon-circle bg-secondary\">\r\n");
      out.write("                                    <i class=\"bi bi-clock-history text-white\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <h3 class=\"card-title text-muted\">Historial</h3>\r\n");
      out.write("                                <p class=\"card-text text-muted\">Revisa tu historial de viajes</p>\r\n");
      out.write("                                <button class=\"btn btn-secondary\" disabled>\r\n");
      out.write("                                    <i class=\"bi bi-lock-fill me-1\"></i> Bloqueado\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <div class=\"mt-2\">\r\n");
      out.write("                                    <span class=\"badge bg-secondary\">Requiere registro</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Call to Action -->\r\n");
      out.write("                <div class=\"row mt-5\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"card border-0 shadow-lg\" style=\"background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\">\r\n");
      out.write("                            <div class=\"card-body text-center p-5 text-white\">\r\n");
      out.write("                                <h2 class=\"fw-bold mb-3\">¿Listo para más?</h2>\r\n");
      out.write("                                <p class=\"fs-5 mb-4\">Crea una cuenta gratis y desbloquea todas las funcionalidades de Enroute AQP</p>\r\n");
      out.write("                                <div class=\"d-flex gap-3 justify-content-center flex-wrap\">\r\n");
      out.write("                                    <a href=\"register.jsp\" class=\"btn btn-warning btn-lg px-5 py-3 rounded-pill fw-bold\">\r\n");
      out.write("                                        <i class=\"bi bi-person-plus-fill me-2\"></i> Registrarse Gratis\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <a href=\"login.jsp\" class=\"btn btn-outline-light btn-lg px-5 py-3 rounded-pill fw-bold\">\r\n");
      out.write("                                        <i class=\"bi bi-box-arrow-in-right me-2\"></i> Iniciar Sesión\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <style>\r\n");
      out.write("        .dashboard-container {\r\n");
      out.write("            max-width: 1400px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .dashboard-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            transition: transform 0.3s, box-shadow 0.3s;\r\n");
      out.write("            border: 1px solid #e0e0e0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .dashboard-card:not(.bg-light):hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 12px 40px rgba(0, 0, 0, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .icon-circle {\r\n");
      out.write("            width: 80px;\r\n");
      out.write("            height: 80px;\r\n");
      out.write("            background-color: #DD6B20;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            margin: 0 auto 1rem;\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            color: white;\r\n");
      out.write("            transition: transform 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .dashboard-card:not(.bg-light):hover .icon-circle {\r\n");
      out.write("            transform: scale(1.1);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-title {\r\n");
      out.write("            font-size: 1.3rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-text {\r\n");
      out.write("            color: #666;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-custom {\r\n");
      out.write("            background-color: #DD6B20;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 0.75rem 2rem;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            border: none;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-custom:hover {\r\n");
      out.write("            background-color: #C55A15;\r\n");
      out.write("            color: white;\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 4px 12px rgba(221, 107, 32, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("        </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <!-- Leaflet JS -->\r\n");
      out.write("    <script src=\"https://unpkg.com/leaflet@1.9.4/dist/leaflet.js\"></script>\r\n");
      out.write("    <!-- Leaflet Routing Machine (para trazar rutas de forma prÃ¡ctica) -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css\" />\r\n");
      out.write("    <script src=\"https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        // Solo ejecutar el cÃ³digo del mapa si existe el elemento #map\r\n");
      out.write("        if (document.getElementById('map')) {\r\n");
      out.write("            // Inicializar el mapa\r\n");
      out.write("            let map;\r\n");
      out.write("            let markers = [];\r\n");
      out.write("            let originMarker = null;\r\n");
      out.write("            let destMarker = null;\r\n");
      out.write("            let routeControl = null;\r\n");
      out.write("            // Bounding box duro para Arequipa (aprox): lon,lat\r\n");
      out.write("            const AQP_BOUNDS = {\r\n");
      out.write("                left: -71.65,   // oeste\r\n");
      out.write("                right: -71.40,  // este\r\n");
      out.write("                top: -16.30,    // norte (mayor lat, menos negativo)\r\n");
      out.write("                bottom: -16.60  // sur (menor lat, mÃ¡s negativo)\r\n");
      out.write("            };\r\n");
      out.write("            function isInAqpBounds(latlng) {\r\n");
      out.write("                if (!latlng) return false;\r\n");
      out.write("                const lat = latlng.lat, lon = latlng.lng;\r\n");
      out.write("                return (\r\n");
      out.write("                    lon >= AQP_BOUNDS.left && lon <= AQP_BOUNDS.right &&\r\n");
      out.write("                    lat >= AQP_BOUNDS.bottom && lat <= AQP_BOUNDS.top\r\n");
      out.write("                );\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            function initMap() {\r\n");
      out.write("                // Centrar el mapa en Arequipa, PerÃº\r\n");
      out.write("                map = L.map('map').setView([-16.4090, -71.5375], 12);\r\n");
      out.write("                \r\n");
      out.write("                // Agregar capa de OpenStreetMap\r\n");
      out.write("                L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {\r\n");
      out.write("                    attribution: 'Â© <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors'\r\n");
      out.write("                }).addTo(map);\r\n");
      out.write("                \r\n");
      out.write("                // Instrucciones mÃ­nimas\r\n");
      out.write("                addHelpControl();\r\n");
      out.write("\r\n");
      out.write("                // Click para elegir origen/destino\r\n");
      out.write("                map.on('click', onMapClick);\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            // Buscar ruta usando los inputs de texto (origen/destino) o marcadores existentes\r\n");
      out.write("            async function buscarRuta() {\r\n");
      out.write("                const btn = document.getElementById('btn-buscar');\r\n");
      out.write("                if (btn) btn.disabled = true;\r\n");
      out.write("                try {\r\n");
      out.write("                    const origenVal = document.getElementById('origen')?.value?.trim();\r\n");
      out.write("                    const destinoVal = document.getElementById('destino')?.value?.trim();\r\n");
      out.write("\r\n");
      out.write("                    // Coordenadas candidatas\r\n");
      out.write("                    let originLatLng = originMarker ? originMarker.getLatLng() : null;\r\n");
      out.write("                    let destLatLng = destMarker ? destMarker.getLatLng() : null;\r\n");
      out.write("\r\n");
      out.write("                    // Geocodificar si hay texto y no hay marcador\r\n");
      out.write("                    if (origenVal && !originLatLng) {\r\n");
      out.write("                        const g = await geocode(origenVal);\r\n");
      out.write("                        if (!g) { alert('Origen no encontrado: ' + origenVal); return; }\r\n");
      out.write("                        originLatLng = L.latLng(parseFloat(g.lat), parseFloat(g.lon));\r\n");
      out.write("                        if (!isInAqpBounds(originLatLng)) {\r\n");
      out.write("                            alert('El origen solicitado estÃ¡ fuera de los lÃ­mites de Arequipa.');\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                    if (destinoVal && !destLatLng) {\r\n");
      out.write("                        const g2 = await geocode(destinoVal);\r\n");
      out.write("                        if (!g2) { alert('Destino no encontrado: ' + destinoVal); return; }\r\n");
      out.write("                        destLatLng = L.latLng(parseFloat(g2.lat), parseFloat(g2.lon));\r\n");
      out.write("                        if (!isInAqpBounds(destLatLng)) {\r\n");
      out.write("                            alert('El destino solicitado estÃ¡ fuera de los lÃ­mites de Arequipa.');\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    if (!originLatLng || !destLatLng) {\r\n");
      out.write("                        // Si ya existen ambos marcadores, dibuja. Si falta alguno, instructivo.\r\n");
      out.write("                        if (originMarker && destMarker) {\r\n");
      out.write("                            drawRoute();\r\n");
      out.write("                        } else {\r\n");
      out.write("                            alert('Proporcione origen y destino (por formulario) o haga clic en el mapa para definirlos.');\r\n");
      out.write("                        }\r\n");
      out.write("                        return;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    // Crear o mover marcadores segÃºn corresponda\r\n");
      out.write("                    if (!originMarker) originMarker = createDraggableMarker(originLatLng, 'Origen'); else originMarker.setLatLng(originLatLng);\r\n");
      out.write("                    if (!destMarker) destMarker = createDraggableMarker(destLatLng, 'Destino'); else destMarker.setLatLng(destLatLng);\r\n");
      out.write("\r\n");
      out.write("                    // Centrar vista entre ambos\r\n");
      out.write("                    try {\r\n");
      out.write("                        const group = L.featureGroup([originMarker, destMarker]);\r\n");
      out.write("                        map.fitBounds(group.getBounds().pad(0.2));\r\n");
      out.write("                    } catch (e) {}\r\n");
      out.write("\r\n");
      out.write("                    // ValidaciÃ³n final por si vinieron de marcadores anteriores\r\n");
      out.write("                    if (!isInAqpBounds(originLatLng) || !isInAqpBounds(destLatLng)) {\r\n");
      out.write("                        alert('Alguno de los puntos estÃ¡ fuera de los lÃ­mites de Arequipa.');\r\n");
      out.write("                        return;\r\n");
      out.write("                    }\r\n");
      out.write("                    drawRoute();\r\n");
      out.write("                } catch (err) {\r\n");
      out.write("                    console.error('Error en buscarRuta:', err);\r\n");
      out.write("                    alert('OcurriÃ³ un error buscando la ruta. Reintenta.');\r\n");
      out.write("                } finally {\r\n");
      out.write("                    if (btn) btn.disabled = false;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Hacer la funciÃ³n accesible globalmente para que el onclick HTML la encuentre en Edge/IE\r\n");
      out.write("            try { window.buscarRuta = buscarRuta; } catch (e) { /* noop */ }\r\n");
      out.write("            \r\n");
      out.write("            // Geocodificador simple usando Nominatim (OpenStreetMap)\r\n");
      out.write("            // Geocodificador simple usando Nominatim (OpenStreetMap)\r\n");
      out.write("            async function geocode(query) {\r\n");
      out.write("                if (!query) return null;\r\n");
      out.write("                // GeocodificaciÃ³n limitada (hard bound) al rectÃ¡ngulo de Arequipa\r\n");
      out.write("                const viewbox = [\r\n");
      out.write("                    AQP_BOUNDS.left,\r\n");
      out.write("                    AQP_BOUNDS.top,\r\n");
      out.write("                    AQP_BOUNDS.right,\r\n");
      out.write("                    AQP_BOUNDS.bottom\r\n");
      out.write("                ].join(',');\r\n");
      out.write("                const params = new URLSearchParams({\r\n");
      out.write("                    format: 'json',\r\n");
      out.write("                    limit: '1',\r\n");
      out.write("                    q: query,\r\n");
      out.write("                    countrycodes: 'pe',\r\n");
      out.write("                    viewbox: viewbox,\r\n");
      out.write("                    bounded: '1'\r\n");
      out.write("                });\r\n");
      out.write("                const url = 'https://nominatim.openstreetmap.org/search?' + params.toString();\r\n");
      out.write("                try {\r\n");
      out.write("                    const resp = await fetch(url, { headers: { 'Accept': 'application/json', 'Accept-Language': 'es' } });\r\n");
      out.write("                    if (!resp.ok) return null;\r\n");
      out.write("                    const data = await resp.json();\r\n");
      out.write("                    if (data && data.length > 0) return data[0];\r\n");
      out.write("                    return null;\r\n");
      out.write("                } catch (e) {\r\n");
      out.write("                    console.error('Geocode error', e);\r\n");
      out.write("                    return null;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function onMapClick(e) {\r\n");
      out.write("                // 1er clic: origen, 2do clic: destino; 3er clic: reinicia y pone nuevo origen\r\n");
      out.write("                if (!originMarker) {\r\n");
      out.write("                    originMarker = createDraggableMarker(e.latlng, 'Origen');\r\n");
      out.write("                } else if (!destMarker) {\r\n");
      out.write("                    destMarker = createDraggableMarker(e.latlng, 'Destino');\r\n");
      out.write("                    drawRoute();\r\n");
      out.write("                } else {\r\n");
      out.write("                    resetRoute();\r\n");
      out.write("                    originMarker = createDraggableMarker(e.latlng, 'Origen');\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function createDraggableMarker(latlng, label) {\r\n");
      out.write("                const marker = L.marker(latlng, { draggable: true }).addTo(map).bindPopup(label).openPopup();\r\n");
      out.write("                markers.push(marker);\r\n");
      out.write("                marker.on('dragend', function() {\r\n");
      out.write("                    if (originMarker && destMarker) {\r\n");
      out.write("                        updateRouteWaypoints();\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                return marker;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function drawRoute() {\r\n");
      out.write("                if (!originMarker || !destMarker || !window.L || !L.Routing) return;\r\n");
      out.write("                if (routeControl) {\r\n");
      out.write("                    try { map.removeControl(routeControl); } catch (_) {}\r\n");
      out.write("                    routeControl = null;\r\n");
      out.write("                }\r\n");
      out.write("                routeControl = L.Routing.control({\r\n");
      out.write("                    waypoints: [originMarker.getLatLng(), destMarker.getLatLng()],\r\n");
      out.write("                    router: L.Routing.osrmv1({ serviceUrl: 'https://router.project-osrm.org/route/v1' }),\r\n");
      out.write("                    show: false,\r\n");
      out.write("                    addWaypoints: false,\r\n");
      out.write("                    draggableWaypoints: true,\r\n");
      out.write("                    routeWhileDragging: true,\r\n");
      out.write("                    fitSelectedRoutes: true\r\n");
      out.write("                }).addTo(map);\r\n");
      out.write("\r\n");
      out.write("                // Mostrar resumen (distancia/tiempo) cuando la ruta sea encontrada\r\n");
      out.write("                routeControl.on('routesfound', function(e) {\r\n");
      out.write("                    try {\r\n");
      out.write("                        if (e && e.routes && e.routes.length > 0) {\r\n");
      out.write("                            const summary = e.routes[0].summary;\r\n");
      out.write("                            const distKm = (summary.totalDistance / 1000).toFixed(2);\r\n");
      out.write("                            const timeMin = Math.round(summary.totalTime / 60);\r\n");
      out.write("                            const infoEl = document.getElementById('route-info');\r\n");
      out.write("                            if (infoEl) infoEl.innerText = `Distancia: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${distKm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" km Â· DuraciÃ³n: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${timeMin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" min`;\r\n");
      out.write("                        }\r\n");
      out.write("                    } catch (err) { console.error('routesfound handler error', err); }\r\n");
      out.write("                });\r\n");
      out.write("                routeControl.on('routingerror', function(err){\r\n");
      out.write("                    console.error('Routing error', err);\r\n");
      out.write("                    const infoEl = document.getElementById('route-info');\r\n");
      out.write("                    if (infoEl) infoEl.innerText = 'No se pudo calcular la ruta.';\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function updateRouteWaypoints() {\r\n");
      out.write("                if (!routeControl) return;\r\n");
      out.write("                routeControl.setWaypoints([originMarker.getLatLng(), destMarker.getLatLng()]);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function resetRoute() {\r\n");
      out.write("                // Eliminar ruta\r\n");
      out.write("                if (routeControl) {\r\n");
      out.write("                    try { map.removeControl(routeControl); } catch (_) {}\r\n");
      out.write("                    routeControl = null;\r\n");
      out.write("                }\r\n");
      out.write("                // Eliminar marcadores creados\r\n");
      out.write("                if (originMarker) { map.removeLayer(originMarker); originMarker = null; }\r\n");
      out.write("                if (destMarker) { map.removeLayer(destMarker); destMarker = null; }\r\n");
      out.write("                // Limpiar array auxiliar si se usa\r\n");
      out.write("                markers.forEach(m => { try { map.removeLayer(m); } catch (_) {} });\r\n");
      out.write("                markers = [];\r\n");
      out.write("                // Limpiar info de ruta\r\n");
      out.write("                const infoEl = document.getElementById('route-info');\r\n");
      out.write("                if (infoEl) infoEl.innerText = '';\r\n");
      out.write("                // Limpiar inputs de bÃºsqueda si existen\r\n");
      out.write("                try {\r\n");
      out.write("                    const o = document.getElementById('origen');\r\n");
      out.write("                    const d = document.getElementById('destino');\r\n");
      out.write("                    if (o) o.value = '';\r\n");
      out.write("                    if (d) d.value = '';\r\n");
      out.write("                } catch (e) { /* noop */ }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function addHelpControl() {\r\n");
      out.write("                // BotÃ³n limpiar y ayuda breve como control Leaflet\r\n");
      out.write("                const HelpControl = L.Control.extend({\r\n");
      out.write("                    options: { position: 'topright' },\r\n");
      out.write("                    onAdd: function() {\r\n");
      out.write("                        const div = L.DomUtil.create('div', 'leaflet-bar');\r\n");
      out.write("                        div.style.background = 'white';\r\n");
      out.write("                        div.style.padding = '8px';\r\n");
      out.write("                        div.style.lineHeight = '1.2';\r\n");
      out.write("                        div.style.minWidth = '200px';\r\n");
      out.write("                        div.innerHTML = `\r\n");
      out.write("                            <div style=\"font-size:12px; margin-bottom:6px;\">\r\n");
      out.write("                                1) Clic para Origen<br/>\r\n");
      out.write("                                2) Clic para Destino<br/>\r\n");
      out.write("                                Puedes arrastrar los marcadores.\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"route-info\" style=\"font-size:12px; margin-bottom:6px; color:#333;\"></div>\r\n");
      out.write("                            <button id=\"btn-clear-route\" class=\"btn btn-sm btn-outline-secondary w-100\">Limpiar ruta</button>\r\n");
      out.write("                        `;\r\n");
      out.write("                        // Evitar que el mapa capture clics sobre el control\r\n");
      out.write("                        L.DomEvent.disableClickPropagation(div);\r\n");
      out.write("                        setTimeout(() => {\r\n");
      out.write("                            const btn = document.getElementById('btn-clear-route');\r\n");
      out.write("                            if (btn) btn.addEventListener('click', resetRoute);\r\n");
      out.write("                        }, 0);\r\n");
      out.write("                        return div;\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                map.addControl(new HelpControl());\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            // Inicializar el mapa cuando cargue la pÃ¡gina\r\n");
      out.write("            document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("                initMap();\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            // Hacer que el mapa se redimensione correctamente\r\n");
      out.write("            window.addEventListener('resize', function() {\r\n");
      out.write("                if (map) {\r\n");
      out.write("                    setTimeout(() => {\r\n");
      out.write("                        map.invalidateSize();\r\n");
      out.write("                    }, 100);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Redimensionar mapa cuando se abra/cierre el offcanvas en mÃ³viles\r\n");
      out.write("            document.getElementById('mobileSidebar')?.addEventListener('hidden.bs.offcanvas', function () {\r\n");
      out.write("                if (map) {\r\n");
      out.write("                    setTimeout(() => {\r\n");
      out.write("                        map.invalidateSize();\r\n");
      out.write("                    }, 100);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Ajustar altura del mapa en mÃ³viles\r\n");
      out.write("            function adjustMapHeight() {\r\n");
      out.write("                const mapElement = document.getElementById('map');\r\n");
      out.write("                if (window.innerWidth < 992) { // MÃ³viles\r\n");
      out.write("                    const viewportHeight = window.innerHeight;\r\n");
      out.write("                    const searchBarHeight = document.querySelector('.bg-white.shadow-sm').offsetHeight;\r\n");
      out.write("                    const mobileHeaderHeight = document.querySelector('.d-lg-none.p-3') ? \r\n");
      out.write("                        document.querySelector('.d-lg-none.p-3').offsetHeight : 0;\r\n");
      out.write("                    const remainingHeight = viewportHeight - searchBarHeight - mobileHeaderHeight;\r\n");
      out.write("                    mapElement.style.height = Math.max(remainingHeight, 300) + 'px';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Ajustar altura al cargar y redimensionar\r\n");
      out.write("            window.addEventListener('load', adjustMapHeight);\r\n");
      out.write("            window.addEventListener('resize', adjustMapHeight);\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /pages/components/DsInicioGuest.jsp(84,52) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userName != null ? sessionScope.userName : 'Invitado'}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent(null);
    // /pages/components/DsInicioGuest.jsp(85,50) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userEmail != null ? sessionScope.userEmail : 'Sin sesión'}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }
}
