/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2025-10-27 23:31:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mapa_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/pages/components/DsFin.jsp", Long.valueOf(1761607900904L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

    Object uid = session.getAttribute("userId");
    if (uid == null) {

      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "components/DsInicioGuest.jsp", out, false);
      out.write('\r');
      out.write('\n');

    } else {

      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "components/DsInicio.jsp", out, false);
      out.write('\r');
      out.write('\n');

    }

      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <!-- Main Content -->\r\n");
      out.write("        <div class=\"flex-grow-1 d-flex flex-column\">\r\n");
      out.write("            <!-- Mobile Header with Menu Button -->\r\n");
      out.write("            <div class=\"bg-white d-lg-none p-3 shadow-sm\">\r\n");
      out.write("                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    <button class=\"btn btn-outline-dark me-3\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#mobileSidebar\">\r\n");
      out.write("                        <i class=\"bi bi-list\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"d-flex align-items-center\">\r\n");
      out.write("                        <i class=\"bi bi-geo-alt-fill text-warning me-2\"></i>\r\n");
      out.write("                        <h5 class=\"mb-0 fw-bold\">Enroute AQP</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Search Bar -->\r\n");
      out.write("            <div class=\"bg-white shadow-sm p-3 p-lg-4\">\r\n");
      out.write("                <div class=\"row g-2 g-lg-3\">\r\n");
      out.write("                    <div class=\"col-12 col-lg-5\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control form-control-lg ps-5\" \r\n");
      out.write("                                   placeholder=\"Lugar de inicio\" id=\"origen\">\r\n");
      out.write("                            <i class=\"bi bi-geo-alt position-absolute top-50 start-0 translate-middle-y ms-3 text-muted\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12 col-lg-5\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control form-control-lg ps-5\" \r\n");
      out.write("                                   placeholder=\"Lugar de destino\" id=\"destino\">\r\n");
      out.write("                            <i class=\"bi bi-geo-alt-fill position-absolute top-50 start-0 translate-middle-y ms-3 text-muted\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12 col-lg-2\">\r\n");
      out.write("                        <button id=\"btn-buscar\" type=\"button\" class=\"btn btn-lg w-100 fw-bold\" style=\"background-color: #DD6B20; color: white;\" onclick=\"buscarRuta()\">\r\n");
      out.write("                            <i class=\"bi bi-search me-2\"></i>\r\n");
      out.write("                            <span class=\"d-none d-sm-inline\">Buscar</span>\r\n");
      out.write("                            <span class=\"d-sm-none\">🔍</span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Map Container -->\r\n");
      out.write("            <div class=\"flex-grow-1 position-relative\">\r\n");
      out.write("                <div id=\"map\" style=\"height: 100%; width: 100%; min-height: 400px;\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <!-- Leaflet JS -->\r\n");
      out.write("    <script src=\"https://unpkg.com/leaflet@1.9.4/dist/leaflet.js\"></script>\r\n");
      out.write("    <!-- Leaflet Routing Machine (para trazar rutas de forma prÃ¡ctica) -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css\" />\r\n");
      out.write("    <script src=\"https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        // Solo ejecutar el cÃ³digo del mapa si existe el elemento #map\r\n");
      out.write("        if (document.getElementById('map')) {\r\n");
      out.write("            // Inicializar el mapa\r\n");
      out.write("            let map;\r\n");
      out.write("            let markers = [];\r\n");
      out.write("            let originMarker = null;\r\n");
      out.write("            let destMarker = null;\r\n");
      out.write("            let routeControl = null;\r\n");
      out.write("            // Bounding box duro para Arequipa (aprox): lon,lat\r\n");
      out.write("            const AQP_BOUNDS = {\r\n");
      out.write("                left: -71.65,   // oeste\r\n");
      out.write("                right: -71.40,  // este\r\n");
      out.write("                top: -16.30,    // norte (mayor lat, menos negativo)\r\n");
      out.write("                bottom: -16.60  // sur (menor lat, mÃ¡s negativo)\r\n");
      out.write("            };\r\n");
      out.write("            function isInAqpBounds(latlng) {\r\n");
      out.write("                if (!latlng) return false;\r\n");
      out.write("                const lat = latlng.lat, lon = latlng.lng;\r\n");
      out.write("                return (\r\n");
      out.write("                    lon >= AQP_BOUNDS.left && lon <= AQP_BOUNDS.right &&\r\n");
      out.write("                    lat >= AQP_BOUNDS.bottom && lat <= AQP_BOUNDS.top\r\n");
      out.write("                );\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            function initMap() {\r\n");
      out.write("                // Centrar el mapa en Arequipa, PerÃº\r\n");
      out.write("                map = L.map('map').setView([-16.4090, -71.5375], 12);\r\n");
      out.write("                \r\n");
      out.write("                // Agregar capa de OpenStreetMap\r\n");
      out.write("                L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {\r\n");
      out.write("                    attribution: 'Â© <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors'\r\n");
      out.write("                }).addTo(map);\r\n");
      out.write("                \r\n");
      out.write("                // Instrucciones mÃ­nimas\r\n");
      out.write("                addHelpControl();\r\n");
      out.write("\r\n");
      out.write("                // Click para elegir origen/destino\r\n");
      out.write("                map.on('click', onMapClick);\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            // Buscar ruta usando los inputs de texto (origen/destino) o marcadores existentes\r\n");
      out.write("            async function buscarRuta() {\r\n");
      out.write("                const btn = document.getElementById('btn-buscar');\r\n");
      out.write("                if (btn) btn.disabled = true;\r\n");
      out.write("                try {\r\n");
      out.write("                    const origenVal = document.getElementById('origen')?.value?.trim();\r\n");
      out.write("                    const destinoVal = document.getElementById('destino')?.value?.trim();\r\n");
      out.write("\r\n");
      out.write("                    // Coordenadas candidatas\r\n");
      out.write("                    let originLatLng = originMarker ? originMarker.getLatLng() : null;\r\n");
      out.write("                    let destLatLng = destMarker ? destMarker.getLatLng() : null;\r\n");
      out.write("\r\n");
      out.write("                    // Geocodificar si hay texto y no hay marcador\r\n");
      out.write("                    if (origenVal && !originLatLng) {\r\n");
      out.write("                        const g = await geocode(origenVal);\r\n");
      out.write("                        if (!g) { alert('Origen no encontrado: ' + origenVal); return; }\r\n");
      out.write("                        originLatLng = L.latLng(parseFloat(g.lat), parseFloat(g.lon));\r\n");
      out.write("                        if (!isInAqpBounds(originLatLng)) {\r\n");
      out.write("                            alert('El origen solicitado estÃ¡ fuera de los lÃ­mites de Arequipa.');\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                    if (destinoVal && !destLatLng) {\r\n");
      out.write("                        const g2 = await geocode(destinoVal);\r\n");
      out.write("                        if (!g2) { alert('Destino no encontrado: ' + destinoVal); return; }\r\n");
      out.write("                        destLatLng = L.latLng(parseFloat(g2.lat), parseFloat(g2.lon));\r\n");
      out.write("                        if (!isInAqpBounds(destLatLng)) {\r\n");
      out.write("                            alert('El destino solicitado estÃ¡ fuera de los lÃ­mites de Arequipa.');\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    if (!originLatLng || !destLatLng) {\r\n");
      out.write("                        // Si ya existen ambos marcadores, dibuja. Si falta alguno, instructivo.\r\n");
      out.write("                        if (originMarker && destMarker) {\r\n");
      out.write("                            drawRoute();\r\n");
      out.write("                        } else {\r\n");
      out.write("                            alert('Proporcione origen y destino (por formulario) o haga clic en el mapa para definirlos.');\r\n");
      out.write("                        }\r\n");
      out.write("                        return;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    // Crear o mover marcadores segÃºn corresponda\r\n");
      out.write("                    if (!originMarker) originMarker = createDraggableMarker(originLatLng, 'Origen'); else originMarker.setLatLng(originLatLng);\r\n");
      out.write("                    if (!destMarker) destMarker = createDraggableMarker(destLatLng, 'Destino'); else destMarker.setLatLng(destLatLng);\r\n");
      out.write("\r\n");
      out.write("                    // Centrar vista entre ambos\r\n");
      out.write("                    try {\r\n");
      out.write("                        const group = L.featureGroup([originMarker, destMarker]);\r\n");
      out.write("                        map.fitBounds(group.getBounds().pad(0.2));\r\n");
      out.write("                    } catch (e) {}\r\n");
      out.write("\r\n");
      out.write("                    // ValidaciÃ³n final por si vinieron de marcadores anteriores\r\n");
      out.write("                    if (!isInAqpBounds(originLatLng) || !isInAqpBounds(destLatLng)) {\r\n");
      out.write("                        alert('Alguno de los puntos estÃ¡ fuera de los lÃ­mites de Arequipa.');\r\n");
      out.write("                        return;\r\n");
      out.write("                    }\r\n");
      out.write("                    drawRoute();\r\n");
      out.write("                } catch (err) {\r\n");
      out.write("                    console.error('Error en buscarRuta:', err);\r\n");
      out.write("                    alert('OcurriÃ³ un error buscando la ruta. Reintenta.');\r\n");
      out.write("                } finally {\r\n");
      out.write("                    if (btn) btn.disabled = false;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Hacer la funciÃ³n accesible globalmente para que el onclick HTML la encuentre en Edge/IE\r\n");
      out.write("            try { window.buscarRuta = buscarRuta; } catch (e) { /* noop */ }\r\n");
      out.write("            \r\n");
      out.write("            // Geocodificador simple usando Nominatim (OpenStreetMap)\r\n");
      out.write("            // Geocodificador simple usando Nominatim (OpenStreetMap)\r\n");
      out.write("            async function geocode(query) {\r\n");
      out.write("                if (!query) return null;\r\n");
      out.write("                // GeocodificaciÃ³n limitada (hard bound) al rectÃ¡ngulo de Arequipa\r\n");
      out.write("                const viewbox = [\r\n");
      out.write("                    AQP_BOUNDS.left,\r\n");
      out.write("                    AQP_BOUNDS.top,\r\n");
      out.write("                    AQP_BOUNDS.right,\r\n");
      out.write("                    AQP_BOUNDS.bottom\r\n");
      out.write("                ].join(',');\r\n");
      out.write("                const params = new URLSearchParams({\r\n");
      out.write("                    format: 'json',\r\n");
      out.write("                    limit: '1',\r\n");
      out.write("                    q: query,\r\n");
      out.write("                    countrycodes: 'pe',\r\n");
      out.write("                    viewbox: viewbox,\r\n");
      out.write("                    bounded: '1'\r\n");
      out.write("                });\r\n");
      out.write("                const url = 'https://nominatim.openstreetmap.org/search?' + params.toString();\r\n");
      out.write("                try {\r\n");
      out.write("                    const resp = await fetch(url, { headers: { 'Accept': 'application/json', 'Accept-Language': 'es' } });\r\n");
      out.write("                    if (!resp.ok) return null;\r\n");
      out.write("                    const data = await resp.json();\r\n");
      out.write("                    if (data && data.length > 0) return data[0];\r\n");
      out.write("                    return null;\r\n");
      out.write("                } catch (e) {\r\n");
      out.write("                    console.error('Geocode error', e);\r\n");
      out.write("                    return null;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function onMapClick(e) {\r\n");
      out.write("                // 1er clic: origen, 2do clic: destino; 3er clic: reinicia y pone nuevo origen\r\n");
      out.write("                if (!originMarker) {\r\n");
      out.write("                    originMarker = createDraggableMarker(e.latlng, 'Origen');\r\n");
      out.write("                } else if (!destMarker) {\r\n");
      out.write("                    destMarker = createDraggableMarker(e.latlng, 'Destino');\r\n");
      out.write("                    drawRoute();\r\n");
      out.write("                } else {\r\n");
      out.write("                    resetRoute();\r\n");
      out.write("                    originMarker = createDraggableMarker(e.latlng, 'Origen');\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function createDraggableMarker(latlng, label) {\r\n");
      out.write("                const marker = L.marker(latlng, { draggable: true }).addTo(map).bindPopup(label).openPopup();\r\n");
      out.write("                markers.push(marker);\r\n");
      out.write("                marker.on('dragend', function() {\r\n");
      out.write("                    if (originMarker && destMarker) {\r\n");
      out.write("                        updateRouteWaypoints();\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                return marker;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function drawRoute() {\r\n");
      out.write("                if (!originMarker || !destMarker || !window.L || !L.Routing) return;\r\n");
      out.write("                if (routeControl) {\r\n");
      out.write("                    try { map.removeControl(routeControl); } catch (_) {}\r\n");
      out.write("                    routeControl = null;\r\n");
      out.write("                }\r\n");
      out.write("                routeControl = L.Routing.control({\r\n");
      out.write("                    waypoints: [originMarker.getLatLng(), destMarker.getLatLng()],\r\n");
      out.write("                    router: L.Routing.osrmv1({ serviceUrl: 'https://router.project-osrm.org/route/v1' }),\r\n");
      out.write("                    show: false,\r\n");
      out.write("                    addWaypoints: false,\r\n");
      out.write("                    draggableWaypoints: true,\r\n");
      out.write("                    routeWhileDragging: true,\r\n");
      out.write("                    fitSelectedRoutes: true\r\n");
      out.write("                }).addTo(map);\r\n");
      out.write("\r\n");
      out.write("                // Mostrar resumen (distancia/tiempo) cuando la ruta sea encontrada\r\n");
      out.write("                routeControl.on('routesfound', function(e) {\r\n");
      out.write("                    try {\r\n");
      out.write("                        if (e && e.routes && e.routes.length > 0) {\r\n");
      out.write("                            const summary = e.routes[0].summary;\r\n");
      out.write("                            const distKm = (summary.totalDistance / 1000).toFixed(2);\r\n");
      out.write("                            const timeMin = Math.round(summary.totalTime / 60);\r\n");
      out.write("                            const infoEl = document.getElementById('route-info');\r\n");
      out.write("                            // Mostrar informaciÃ³n de la ruta\r\n");
      out.write("                            // distKm se muestra como objeto y no como valor\r\n");
      out.write("                            if (infoEl) infoEl.innerText = `Distancia: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${distKm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" km - Duracion: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${timeMin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" min`;\r\n");
      out.write("                        }\r\n");
      out.write("                    } catch (err) { console.error('routesfound handler error', err); }\r\n");
      out.write("                });\r\n");
      out.write("                routeControl.on('routingerror', function(err){\r\n");
      out.write("                    console.error('Routing error', err);\r\n");
      out.write("                    const infoEl = document.getElementById('route-info');\r\n");
      out.write("                    if (infoEl) infoEl.innerText = 'No se pudo calcular la ruta.';\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function updateRouteWaypoints() {\r\n");
      out.write("                if (!routeControl) return;\r\n");
      out.write("                routeControl.setWaypoints([originMarker.getLatLng(), destMarker.getLatLng()]);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function resetRoute() {\r\n");
      out.write("                // Eliminar ruta\r\n");
      out.write("                if (routeControl) {\r\n");
      out.write("                    try { map.removeControl(routeControl); } catch (_) {}\r\n");
      out.write("                    routeControl = null;\r\n");
      out.write("                }\r\n");
      out.write("                // Eliminar marcadores creados\r\n");
      out.write("                if (originMarker) { map.removeLayer(originMarker); originMarker = null; }\r\n");
      out.write("                if (destMarker) { map.removeLayer(destMarker); destMarker = null; }\r\n");
      out.write("                // Limpiar array auxiliar si se usa\r\n");
      out.write("                markers.forEach(m => { try { map.removeLayer(m); } catch (_) {} });\r\n");
      out.write("                markers = [];\r\n");
      out.write("                // Limpiar info de ruta\r\n");
      out.write("                const infoEl = document.getElementById('route-info');\r\n");
      out.write("                if (infoEl) infoEl.innerText = '';\r\n");
      out.write("                // Limpiar inputs de bÃºsqueda si existen\r\n");
      out.write("                try {\r\n");
      out.write("                    const o = document.getElementById('origen');\r\n");
      out.write("                    const d = document.getElementById('destino');\r\n");
      out.write("                    if (o) o.value = '';\r\n");
      out.write("                    if (d) d.value = '';\r\n");
      out.write("                } catch (e) { /* noop */ }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function addHelpControl() {\r\n");
      out.write("                // BotÃ³n limpiar y ayuda breve como control Leaflet\r\n");
      out.write("                const HelpControl = L.Control.extend({\r\n");
      out.write("                    options: { position: 'topright' },\r\n");
      out.write("                    onAdd: function() {\r\n");
      out.write("                        const div = L.DomUtil.create('div', 'leaflet-bar');\r\n");
      out.write("                        div.style.background = 'white';\r\n");
      out.write("                        div.style.padding = '8px';\r\n");
      out.write("                        div.style.lineHeight = '1.2';\r\n");
      out.write("                        div.style.minWidth = '200px';\r\n");
      out.write("                        div.innerHTML = `\r\n");
      out.write("                            <div style=\"font-size:12px; margin-bottom:6px;\">\r\n");
      out.write("                                1) Clic para Origen<br/>\r\n");
      out.write("                                2) Clic para Destino<br/>\r\n");
      out.write("                                Puedes arrastrar los marcadores.\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"route-info\" style=\"font-size:12px; margin-bottom:6px; color:#333;\"></div>\r\n");
      out.write("                            <button id=\"btn-clear-route\" class=\"btn btn-sm btn-outline-secondary w-100\">Limpiar ruta</button>\r\n");
      out.write("                        `;\r\n");
      out.write("                        // Evitar que el mapa capture clics sobre el control\r\n");
      out.write("                        L.DomEvent.disableClickPropagation(div);\r\n");
      out.write("                        setTimeout(() => {\r\n");
      out.write("                            const btn = document.getElementById('btn-clear-route');\r\n");
      out.write("                            if (btn) btn.addEventListener('click', resetRoute);\r\n");
      out.write("                        }, 0);\r\n");
      out.write("                        return div;\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                map.addControl(new HelpControl());\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            // Inicializar el mapa cuando cargue la pÃ¡gina\r\n");
      out.write("            document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("                initMap();\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            // Hacer que el mapa se redimensione correctamente\r\n");
      out.write("            window.addEventListener('resize', function() {\r\n");
      out.write("                if (map) {\r\n");
      out.write("                    setTimeout(() => {\r\n");
      out.write("                        map.invalidateSize();\r\n");
      out.write("                    }, 100);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Redimensionar mapa cuando se abra/cierre el offcanvas en mÃ³viles\r\n");
      out.write("            document.getElementById('mobileSidebar')?.addEventListener('hidden.bs.offcanvas', function () {\r\n");
      out.write("                if (map) {\r\n");
      out.write("                    setTimeout(() => {\r\n");
      out.write("                        map.invalidateSize();\r\n");
      out.write("                    }, 100);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Ajustar altura del mapa en mÃ³viles\r\n");
      out.write("            function adjustMapHeight() {\r\n");
      out.write("                const mapElement = document.getElementById('map');\r\n");
      out.write("                if (window.innerWidth < 992) { // MÃ³viles\r\n");
      out.write("                    const viewportHeight = window.innerHeight;\r\n");
      out.write("                    const searchBarHeight = document.querySelector('.bg-white.shadow-sm').offsetHeight;\r\n");
      out.write("                    const mobileHeaderHeight = document.querySelector('.d-lg-none.p-3') ? \r\n");
      out.write("                        document.querySelector('.d-lg-none.p-3').offsetHeight : 0;\r\n");
      out.write("                    const remainingHeight = viewportHeight - searchBarHeight - mobileHeaderHeight;\r\n");
      out.write("                    mapElement.style.height = Math.max(remainingHeight, 300) + 'px';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Ajustar altura al cargar y redimensionar\r\n");
      out.write("            window.addEventListener('load', adjustMapHeight);\r\n");
      out.write("            window.addEventListener('resize', adjustMapHeight);\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
